name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        run: |
          curl -fsSL https://render.com/deploy | bash
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
